INSERT INTO TB_CIDADE(NOME,ESTADO) VALUES ('Goiana', 'PE');
INSERT INTO TB_CIDADE(NOME,ESTADO) VALUES ('João Pessoa', 'PB');
INSERT INTO TB_CIDADE(NOME,ESTADO) VALUES ('Areia Branca', 'PB');
INSERT INTO TB_CLIENTE(NOME,SEXO,DATA_NASCIMENTO,ID_CIDADE_MORA ) VALUES ('Josefa da Silva', 'F', '1972-09-08',1);